[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# Här definierar vi alla externa bibliotek som behövs för sensorerna och MQTT
lib_deps = 
	adafruit/Adafruit SHT31 Library @ ^2.2.2
	milesburton/DallasTemperature @ ^3.11.0
	paulstoffregen/OneWire @ ^2.3.7
	knolleary/PubSubClient @ ^2.8
    SPI
    